<?php

function print_f($value)
{
	$t = explode(" ", microtime());
	
	$output = print_r($value, true);
	file_put_contents('logs.txt', $output . PHP_EOL, FILE_APPEND | LOCK_EX);;
}


class Dir
{
	public function __construct(
		public string $directory,
	) {
	}
	
	public function isDir(): bool
	{
		return is_dir($this->directory);
	}
	
	public function scan(): array
	{
		$result = [];
		$cdir = scandir($this->directory);
		foreach ($cdir as $key => $value) {
			if (!in_array($value, array(".", ".."))) {
				if (is_dir($this->directory . DIRECTORY_SEPARATOR . $value)) {
					$result[$value] = $this->scan($this->directory . DIRECTORY_SEPARATOR . $value);
				} else {
					$result[] = str_replace('.php', '', $value);
				}
			}
		}
		
		return $result;
	}
}

class TitleCaseReplace
{
	
	public static function convert($string)
	{
		
		$delimiters = array(" ", "-", ".", "'", "O'", "Mc");
		$exceptions = [
			"and",
			"to",
			"of",
			"de",
			"da",
			"das",
			"do",
			"dos",
			"em",
			"por",
			"a",
			"ao",
			"à",
			"àos",
			"às",
			"nas",
			"na",
			"I",
			"II",
			"III",
			"IV",
			"V",
			"VI",
			"e",
			"LTDA",
			"EPP",
			"subcategoria",
			"subtipo",
			"para",
			"pra",
			"S/A",
			"N/D",
			"DB",
			"R$",
			"n°",
			"SCM",
			"SVA",
		];
		
		$string = mb_convert_case($string, MB_CASE_TITLE, "UTF-8");
		foreach ($delimiters as $dlnr => $delimiter) {
			$words = explode($delimiter, $string);
			$newwords = array();
			foreach ($words as $wordnr => $word) {
				if ($wordnr == 0) {
					$word = ucfirst($word);
				} elseif (in_array(mb_strtoupper($word, "UTF-8"), $exceptions)) {
					// check exceptions list for any words that should be in upper case
					$word = mb_strtoupper($word, "UTF-8");
				} elseif (in_array(mb_strtolower($word, "UTF-8"), $exceptions)) {
					// check exceptions list for any words that should be in upper case
					$word = mb_strtolower($word, "UTF-8");
				} elseif (!in_array($word, $exceptions)) {
					// convert to uppercase (non-utf8 only)
					$word = ucfirst($word);
				}
				array_push($newwords, $word);
			}
			$string = join($delimiter, $newwords);
		}
		
		return $string;
	}
	
}

$path = '/mnt/f/tmp/psx-roms';

$path_itens = (new Dir($path))->scan();

$names = [];

$original = ["102 Dalmatians Puppies to The Rescue.7z",
	"2Xtreme.7z",
	"3D Baseball.7z",
	"3Xtreme.7z",
	"40 Winks.7z",
	"A Train.rar",
	"Ace Combat 2 e Sces 00699 .Rar.rar",
	"Ace Combat 2.rar",
	"Ace Combat 3 Electrosphere.rar",
	"Aces of The Air.rar",
	"Action Bass.7z",
	"Action Man Operation Extreme.rar",
	"Activision Classics.7z",
	"Adidas Power Soccer 98.rar",
	"Adidas Power Soccer Scus 94502 .Rar.rar",
	"Adventure of Phix.rar",
	"Adventures of Lomax.rar",
	"Agile Warrior F 111X.rar",
	"Air Combat.rar",
	"Air Hockey.rar",
	"Akuji The Heartless.rar",
	"Alexi Lalas International Soccer.rar",
	"Alien Resurrection.rar",
	"Alien Trilogy.rar",
	"All Star Baseball.rar",
	"All Star Racing 2.rar",
	"All Star Racing.rar",
	"All Star Slammin Dodgeball.7z",
	"Allied General.rar",
	"Alone In The Dark One Eyed Jack S Revenge.rar",
	"Alone In The Dark The New Nightmare Disc1Of2.rar",
	"Alone In The Dark The New Nightmare Disc2Of2.rar",
	"Alundra 2.rar",
	"Alundra e Sles 01135 .Rar.rar",
	"Alundra.rar",
	"Amazing Virtual Sea Monkeys.rar",
	"American Pool.rar",
	"Andretti Racing.rar",
	"Animaniacs Ten Pin Alley 2.rar",
	"Animorphs Shattered Reality.rar",
	"Ape Escape.rar",
	"Apocalypse.rar",
	"Aquanaut S Holiday.rar",
	"Arc The Lad Collection Making of Disc.rar",
	"Arc The Lad II.rar",
	"Arc The Lad III Disc1Of2.rar",
	"Arc The Lad III Disc2Of2.rar",
	"Arc The Lad Monster Tournament Battle Arena.7z",
	"Arc The Lad.rar",
	"Arcade Party Pack.rar",
	"Arcade S Greatest Hits Midway 2.rar",
	"Arcade S Greatest Hits The Atari Collection 1.rar",
	"Arcade S Greatest Hits The Atari Collection 2.rar",
	"Arcade S Greatest Hits Williams.rar",
	"Area 51.rar",
	"Armored Core Master of Arena Disc1Of2.rar",
	"Armored Core Master of Arena Disc2Of2.rar",
	"Armored Core Project Phantasma.rar",
	"Armored Core.rar",
	"Armorines Project Swarm.rar",
	"Army Men 3D.rar",
	"Army Men Air Attack 2.rar",
	"Army Men Air Attack.rar",
	"Army Men Green Rouge.rar",
	"Army Men Sarge S Heroes 2.7z",
	"Army Men Sarge S Heroes.rar",
	"Army Men World War Final Front.rar",
	"Army Men World War Land Sea Air.rar",
	"Army Men World War Team Assault.7z",
	"Army Men World War.rar",
	"Arthur Ready to Race.rar",
	"Assault Retribution.rar",
	"Assault Rigs.rar",
	"Asteroids 3D.rar",
	"Atari 30Th Aniversary Edition Redux.rar",
	"Attack of The Saucerman.rar",
	"Atv Mania.rar",
	"Atv Quad Power Racing.rar",
	"Atv Racers.rar",
	"Austin Powers Pinball.7z",
	"Auto Destruct.rar",
	"Azure Dreams.7z",
	"Backstreet Billiards.7z",
	"Backyard Soccer.7z",
	"Baldies.7z",
	"Ball Breakers.7z",
	"Ballblazer Champions.7z",
	"Ballerburg Castle Chaos.7z",
	"Ballistic.7z",
	"Barbie Detective The Mystery Cruise.7z",
	"Barbie Explorer.7z",
	"Barbie Gotta Have Games.rar",
	"Barbie Race Ride.7z",
	"Barbie Super Sports.7z",
	"Bases Loaded 96 Double Header.rar",
	"Bass Landing.7z",
	"Bassrise Fishing.7z",
	"Batman Beyond Return of The Joker.rar",
	"Batman Forever The Arcade Game.7z",
	"Batman Gotham City Racer.7z",
	"Batman Robin.7z",
	"Battle Arena Toshinden 2.rar",
	"Battle Arena Toshinden 3.7z",
	"Battle Arena Toshinden.rar",
	"Battle Hunter.7z",
	"Battlesport.rar",
	"Battlestations.7z",
	"Battletanx Global Assault.7z",
	"Bear In The Big Blue House.7z",
	"Beast Wars Transformers.7z",
	"Beyblade.rar",
	"Beyond The Beyond.7z",
	"Big Air.7z",
	"Big Bass Fishing.rar",
	"Big Bass World Championship.7z",
	"Big League Slugger Baseball.7z",
	"Big Strike Bowling.7z",
	"Billiards.7z",
	"Bio F.R.e.a.K.S..7z",
	"Black Bass With Blue Marlin.7z",
	"Black Dawn.rar",
	"Blade.7z",
	"Blast Chamber.7z",
	"Blast Lacrosse.7z",
	"Blast Radius.rar",
	"Blaster Master Blasting Again.7z",
	"Blasto.7z",
	"Blazing Dragons.7z",
	"Blockids.rar",
	"Blood Omen Legacy of Kain.7z",
	"Bloody Roar 2.7z",
	"Bloody Roar.7z",
	"Blue S Clues Blue S Big Musical.7z",
	"Bob The Builder Can We Fix It.7z",
	"Bogey Dead 6.rar",
	"Bomberman Fantasy Race.7z",
	"Bomberman Party Edition.7z",
	"Bomberman World.7z",
	"Bombing Islands.7z",
	"Boombots.7z",
	"Bottom of The Ninth 97.7z",
	"Bottom of The Ninth 99.7z",
	"Bottom of The Ninth.7z",
	"Bowling.7z",
	"Boxing.7z",
	"Brahma Force.7z",
	"Brain Dead 13 Disc1Of2.7z",
	"Brain Dead 13 Disc2Of2.7z",
	"Bratz.7z",
	"Brave Fencer Musashi Bonus Disc Squaresoft 98 Collector S Cd Vol.2 Final Fantasy Viii.7z",
	"Brave Fencer Musashi.7z",
	"Bravo Air Race.7z",
	"Breakout.rar",
	"Breath of Fire III.7z",
	"Breath of Fire IV.7z",
	"Brigandine Legend of Forsena.7z",
	"Broken Helix.7z",
	"Broken Sword 2 The Smoking Mirror.7z",
	"Broken Sword The Shadow of The Templars.7z",
	"Brunswick Circuit Pro Bowling 2.rar",
	"Brunswick Circuit Pro Bowling.rar",
	"Bubble Bobble Featuring Rainbow Islands.7z",
	"Bubsy 3D.7z",
	"Bugriders The Race of Kings.7z",
	"Bugs Bunny Lost In Time.7z",
	"Bugs Bunny Taz Time Busters.7z",
	"Builder S Block.7z",
	"Burning Road.rar",
	"Burstrick Wake Boarding.7z",
	"Bushido Blade 2.7z",
	"Bushido Blade.7z",
	"Bust a Groove 2.7z",
	"Bust a Groove.7z",
	"Bust a Move 2 Arcade Edition.rar",
	"Bust a Move 4.rar",
	"Bust a Move 99.rar",
	"Buster Bros. Collection.7z",
	"C 12 The Final Resistance.rar",
	"C The Contra Adventure.rar",
	"Cabela S Big Game Hunter Ultimate Challenge.zip",
	"Cabela S Ultimate Deer Hunt.rar",
	"Caesar S Palace 2000.rar",
	"Caesar S Palace II.rar",
	"Caesar S Palace.rar",
	"Capcom Vs. Snk Millennium Fight 2000 Pro.rar",
	"Card Games.rar",
	"Cardinal Syn.rar",
	"Carnage Heart Disc1Of2.rar",
	"Carnage Heart Disc2Of2.rar",
	"Cart World Series.rar",
	"Casper Friends Around The World.rar",
	"Casper.rar",
	"Castlevania Chronicles.zip",
	"Castlevania Symphony of The Night Plus Music Cd.rar",
	"Castrol Honda Superbike Racing.rar",
	"Cat In The Hat.rar",
	"Centipede.rar",
	"Championship Bass.zip",
	"Championship Motocross 2001 Ricky Carmichael.rar",
	"Championship Motocross Featuring Ricky Carmichael.rar",
	"Championship Surfer.rar",
	"Chess.rar",
	"Chessmaster 3D.rar",
	"Chessmaster II.rar",
	"Chicken Run.rar",
	"Chocobo Racing.rar",
	"Chocobo S Dungeon 2.rar",
	"Chronicles of The Sword Disc1Of2.rar",
	"Chronicles of The Sword Disc2Of2.rar",
	"Chrono Cross Disc1Of2.rar",
	"Chrono Cross Disc2Of2.rar",
	"Circuit Breakers.rar",
	"City of Lost Children.rar",
	"Civilization II.rar",
	"Cleopatra S Fortune.rar",
	"Clock Tower II The Struggle Within.rar",
	"Clock Tower.rar",
	"Codename Tenka.rar",
	"Colin McRae Rally 2.0.rar",
	"Colin McRae Rally.rar",
	"College Slam.rar",
	"Colony Wars Disc1Of2.rar",
	"Colony Wars Disc2Of2.rar",
	"Colony Wars III Red Sun.rar",
	"Colony Wars Vengeance.rar",
	"Command Conquer Gdi Disc.rar",
	"Command Conquer Nod Disc.rar",
	"Command Conquer Red Alert Allies Disc.rar",
	"Command Conquer Red Alert Retaliation Allies Disc.rar",
	"Command Conquer Red Alert Retaliation Soviets Disc.rar",
	"Command Conquer Red Alert Soviets Disc.rar",
	"Contender 2.rar",
	"Contender.rar",
	"Contra Legacy of War.rar",
	"Cool Boarders 2.rar",
	"Cool Boarders 2001.7z",
	"Cool Boarders 3.rar",
	"Cool Boarders 4.7z",
	"Cool Boarders Extreme Snowboarding.rar",
	"Countdown Vampires Disc1Of2.rar",
	"Countdown Vampires Disc2Of2.rar",
	"Courier Crisis.rar",
	"Covert Ops Nuclear Dawn Disc1Of2.rar",
	"Covert Ops Nuclear Dawn Disc2Of2.rar",
	"Crash Bandicoot 2 Cortex Strikes Back.rar",
	"Crash Bandicoot 3 Warped.rar",
	"Crash Bandicoot.rar",
	"Crash Bash.rar",
	"Crash Team Racing.rar",
	"Creatures Raised In Space.rar",
	"Creatures.rar",
	"Crime Killer.rar",
	"Critical Depth.rar",
	"Criticom.rar",
	"Croc 2.rar",
	"Croc Legend of The Gobbos.rar",
	"Crossroad Crisis.7z",
	"Crow The City of Angels.rar",
	"Crusader No Remorse.rar",
	"Crusaders of Might Magic.rar",
	"Crypt Killer.rar",
	"Cubix Robots For Everyone Race N Robots.rar",
	"Cyber Speed.zip",
	"Cyberia.rar",
	"Cybersled.rar",
	"Cybertiger Golf.rar",
	"D Disc1Of3.rar",
	"D Disc2Of3.rar",
	"D Disc3Of3.rar",
	"Dance Dance Revolution Disney Mix.rar",
	"Dance Dance Revolution Konamix.rar",
	"Dance Dance Revolution Usa Mix.rar",
	"Danger Girl.rar",
	"Dare Devil Derby 3D.rar",
	"Darklight Conflict.rar",
	"Darkstalkers 3 Jedah S Damnation.rar",
	"Darkstalkers The Night Warriors.rar",
	"Darkstone Evil Reigns.rar",
	"Dave Mirra Freestyle Bmx Maximum Remix.rar",
	"Dave Mirra Freestyle Bmx.rar",
	"David Beckham Soccer.rar",
	"Dead Ball Zone.rar",
	"Dead In The Water.rar",
	"Dead Or Alive.rar",
	"Deathtrap Dungeon.rar",
	"Deception III Dark Delusion.rar",
	"Defcon 5 Peace Has a Price.rar",
	"Delta Force Urban Warfare.rar",
	"Demolition Racer.rar",
	"Descent Maximum.rar",
	"Descent.rar",
	"Destrega.rar",
	"Destruction Derby 2.rar",
	"Destruction Derby Raw.rar",
	"Destruction Derby.rar",
	"Deuce.rar",
	"Devil Dice.rar",
	"Dexter S Laboratory Mandark S Lab.rar",
	"Diablo.rar",
	"Die Hard Trilogy 2.rar",
	"Die Hard Trilogy.rar",
	"Digimon Digital Card Battle.rar",
	"Digimon Rumble Arena.rar",
	"Digimon World 2.rar",
	"Digimon World 3.rar",
	"Digimon World.rar",
	"Dino Crisis 2.rar",
	"Dino Crisis.rar",
	"Dirt Jockey Heavy Equipment Operator.rar",
	"Discworld II Mortality Bytes.rar",
	"Discworld.rar",
	"Disney S 101 Dalmations II Patch S London Adventure.rar",
	"Disney S a Bug S Life.rar",
	"Disney S Aladdin Nasira S Revenge.rar",
	"Disney S Atlantis The Lost Empire.rar",
	"Disney S Buzz Lightyear of Star Command.rar",
	"Disney S Dinosaur.rar",
	"Disney S Goofy S Fun House.rar",
	"Disney S Hercules.rar",
	"Disney S Lilo Stitch.rar",
	"Disney S Mulan Story Studio.rar",
	"Disney S Peter Pan In Return to Neverland.rar",
	"Disney S Pooh S Party Game In Search of The Treasure.rar",
	"Disney S Tarzan.rar",
	"Disney S The Emperor S New Groove.zip",
	"Disney S The Jungle Book Rhythm N Groove Party.rar",
	"Disney S The Lion King II Simba S Mighty Adventure.rar",
	"Disney S The Little Mermaid II.rar",
	"Disney S The Road to El Dorado Gold Glory.rar",
	"Disney S Tigger S Honey Hunt.7z",
	"Disney S Toy Story 2 Buzz Lightyear to The Rescue.rar",
	"Disney S Toy Story Racer.rar",
	"Disney S Treasure Planet.rar",
	"Disney World Quest Magical Racing Tour.rar",
	"Disruptor.rar",
	"Divide The Enemies Within.rar",
	"Donald Duck Goin Quackers.rar",
	"Doom.rar",
	"Dora The Explorer Barnyard Buddies.rar",
	"Dracula 2 The Last Sanctuary Disc1Of2.zip",
	"Dracula 2 The Last Sanctuary Disc2Of2.zip",
	"Dracula The Resurrection Disc1Of2.rar",
	"Dracula The Resurrection Disc2Of2.rar",
	"Dragon Seeds.7z",
	"Dragon Tales Dragon Seek.rar",
	"Dragon Valor Disc1Of2.rar",
	"Dragon Valor Disc2Of2.rar",
	"Dragon Warrior Vii Disc1Of2.rar",
	"Dragon Warrior Vii Disc2Of2.rar",
	"Dragonball Gt Final Bout.rar",
	"Dragonball Z Ultimate Battle 22.rar",
	"Dragonheart Fire Steel.rar",
	"Driver 2 Disc1Of2.rar",
	"Driver 2 Disc2Of2.rar",
	"Driver.rar",
	"Ducati World Racing.rar",
	"Duke Nukem Land of The Babes.rar",
	"Duke Nukem Time to Kill.rar",
	"Duke Nukem Total Meltdown.rar",
	"Dukes of Hazzard II Daisy Dukes It Out.rar",
	"Dukes of Hazzard.rar",
	"Dune 2000.rar",
	"Dynasty Warriors.rar",
	"Eagle One Harrier Attack.rar",
	"Easter Bunny S Big Day.7z",
	"Echo Nights.rar",
	"Ecw Anarchy Rulz.rar",
	"Ecw Hardcore Revolution.zip",
	"Eggs of Steel.rar",
	"Ehrgeiz God Bless The Ring.rar",
	"Einhander.rar",
	"Elemental Gearbolt.rar",
	"Eliminator.rar",
	"Elmo S Letter Adventure.rar",
	"Elmo S Number Journey.rar",
	"Epidemic.rar",
	"Equestrian Showcase.zip",
	"Espn Extreme Games.zip",
	"Espn Mls Gamenight.zip",
	"Espn X Games Proboarder.rar",
	"Et The Extra Terrestrial Interplanetary Mission.rar",
	"Eternal Eyes.rar",
	"Evil Dead Hail to The King Disc1Of2.rar",
	"Evil Dead Hail to The King Disc2Of2.rar",
	"Evil Zone.rar",
	"Excalibur 2555 A.D..rar",
	"Extreme Go Kart Racing.rar",
	"Extreme Pinball.rar",
	"F1 2000.7z",
	"F1 World Grand Prix 2000.7z",
	"F1 World Grand Prix.7z",
	"Fade 2 Black.7z",
	"Family Card Game Fun Pak.7z",
	"Family Feud.7z",
	"Family Game Pack.7z",
	"Fantastic Four.rar",
	"Fatal Fury Wild Ambition.7z",
	"Fear Effect 2 Retro Helix Disc1Of4.7z",
	"Fear Effect 2 Retro Helix Disc2Of4.7z",
	"Fear Effect 2 Retro Helix Disc3Of4.7z",
	"Fear Effect 2 Retro Helix Disc4Of4.7z",
	"Fear Effect Disc1Of4.7z",
	"Fear Effect Disc2Of4.7z",
	"Fear Effect Disc3Of4.7z",
	"Fear Effect Disc4Of4.7z",
	"Felony 11 79.7z",
	"Fifa 2000 Major League Soccer.7z",
	"Fifa 2001 Major League Soccer.7z",
	"Fifa 2002.7z",
	"Fifa 96.7z",
	"Fifa 99.7z",
	"Fifa Road to World Cup 98.7z",
	"Fifa Soccer 2003.7z",
	"Fifa Soccer 2004.7z",
	"Fifa Soccer 2005.7z",
	"Fifa Soccer 97.7z",
	"Fifa World Cup 2002.7z",
	"Fifth Element The.7z",
	"Fighter Maker.7z",
	"Fighting Force 2.7z",
	"Fighting Force.rar",
	"Final Doom.rar",
	"Final Fantasy Anthology Final Fantasy V Disc.7z",
	"Final Fantasy Anthology Final Fantasy VI Disc.7z",
	"Final Fantasy Chronicles Chrono Trigger Disc.7z",
	"Final Fantasy Chronicles Final Fantasy IV Disc.7z",
	"Final Fantasy Ix Disc1Of4.7z",
	"Final Fantasy Ix Disc2Of4.7z",
	"Final Fantasy Ix Disc3Of4.7z",
	"Final Fantasy Ix Disc4Of4.7z",
	"Final Fantasy Origins.7z",
	"Final Fantasy Tactics.7z",
	"Final Fantasy Vii Disc1Of3.7z",
	"Final Fantasy Vii Disc2Of3.7z",
	"Final Fantasy Vii Disc3Of3.7z",
	"Final Fantasy Viii Disc1Of4.7z",
	"Final Fantasy Viii Disc2Of4.7z",
	"Final Fantasy Viii Disc3Of4.7z",
	"Final Fantasy Viii Disc4Of4.7z",
	"Final Round The.7z",
	"Fisherman S Bait 2 Big Ol Bass.7z",
	"Fisherman S Bait Big Ol Bass 2.7z",
	"Fisherman S Bait.7z",
	"Flintstones Bedrock Bowling.rar",
	"Floating Runner Quest For The 7 Crystals.rar",
	"Ford Racing.7z",
	"Ford Truck Mania.7z",
	"Formula 1 98.7z",
	"Formula 1 Championship Edition.7z",
	"Formula 1 Championship Season 2000.7z",
	"Formula 1.7z",
	"Formula One 2000.7z",
	"Formula One 99.7z",
	"Forsaken.rar",
	"Fox Hunt Disc1Of3.7z",
	"Fox Hunt Disc2Of3.7z",
	"Fox Hunt Disc3Of3.7z",
	"Fox Sports Golf 99.rar",
	"Fox Sports Nhl Championship 2000.7z",
	"Fox Sports Soccer 99.7z",
	"Frank Thomas Big Hurt Baseball.7z",
	"Freestyle Boardin 99.rar",
	"Frogger 2 Swampy S Revenge.7z",
	"Frogger.7z",
	"Front Mission 3.7z",
	"Future Cop L.a.P.D..7z",
	"G Darius.rar",
	"G Police 2 Weapons of Justice.rar",
	"G Police Disc1Of2.7z",
	"G Police Disc2Of2.7z",
	"Galaga Destination Earth.rar",
	"Galerians Disc1Of3.rar",
	"Galerians Disc2Of3.rar",
	"Galerians Disc3Of3.rar",
	"Gallop Racer.rar",
	"Game of Life The.rar",
	"Gauntlet Legends.rar",
	"Gekido Urban Fighters.rar",
	"Gekioh Shooting King.7z",
	"Geom Cube.rar",
	"Gex 2 Enter The Gecko.rar",
	"Gex 3 Deep Cover Gecko.rar",
	"Gex.rar",
	"Ghost In The Shell.rar",
	"Global Domination.rar",
	"Glover.rar",
	"Goal Storm 97.rar",
	"Goal Storm.rar",
	"Golden Nugget Disc1Of2.rar",
	"Golden Nugget Disc2Of2.rar",
	"Golden Tee Golf Peter Jacobson S.rar",
	"Gran Turismo 2 Arcade Disc.zip",
	"Gran Turismo 2 Simulation Disc.rar",
	"Gran Turismo.rar",
	"Grand Slam 97.rar",
	"Grand Theft Auto 2.rar",
	"Grand Theft Auto Mission Pack 1 London 1969.rar",
	"Grand Theft Auto Original Director S Cut.rar",
	"Grand Tour Racing 98.rar",
	"Grandia Disc1Of2.zip",
	"Grandia Disc2Of2.rar",
	"Granstream Saga The.rar",
	"Grid Runner.rar",
	"Grinch The.rar",
	"Grind Session.rar",
	"Grudge Warriors.rar",
	"Guardian S Crusade.rar",
	"Gubble.rar",
	"Guilty Gear.rar",
	"Gundam Battle Assault 2.rar",
	"Gundam Battle Assault.rar",
	"Gunfighter The Legend of Jesse James.rar",
	"Gunship.rar",
	"Hardball 5.7z",
	"Hardball 99.rar",
	"Harry Potter and The Chamber of Secrets.rar",
	"Harry Potter The Sorcerer S Stone.rar",
	"Harvest Moon Back to Nature.rar",
	"Hbo Boxing.rar",
	"Heart of Darkness Disc1Of2.rar",
	"Heart of Darkness Disc2Of2.rar",
	"Hellboy Asylum Seeker.rar",
	"Hello Kitty Cube Frenzy.rar",
	"Herc S Adventures.7z",
	"Hexen.rar",
	"Hi Octane The Track Fights Back.rar",
	"High Heat Baseball 2000.rar",
	"High Heat Major League Baseball 2002.rar",
	"Hive The Disc1Of2.rar",
	"Hive The Disc2Of2.rar",
	"Hogs of War.rar",
	"Hooters Road Trip.rar",
	"Hoshigami Running Blue Earth.rar",
	"Hot Shots Golf 2.rar",
	"Hot Shots Golf.rar",
	"Hot Wheels Extreme Racing.rar",
	"Hot Wheels Turbo Racing.rar",
	"Hugo The Evil Mirror.rar",
	"Hydro Thunder.7z",
	"Ihra Drag Racing.7z",
	"Impact Racing.rar",
	"In Cold Blood 2 Discs.7z",
	"In The Hunt.7z",
	"Incredible Crisis.7z",
	"Incredible Hulk The Pantheon Saga.7z",
	"Independence Day.rar",
	"Inspector Gadget Gadget S Crazy Maze.rar",
	"Intelligent Qube.7z",
	"Intellivision Classics.7z",
	"International Track Field 2000.7z",
	"International Track Field.7z",
	"Interplay Sports Baseball 2000.7z",
	"Inuyasha a Feudal Fairy Tale.7z",
	"Invasion From Beyond B Movie.7z",
	"Iron Blood Warriors of Ravenloft.7z",
	"Iron Soldier 3.7z",
	"Ironman X O Manowar In Heavy Metal.rar",
	"Irritating Stick.7z",
	"Iss Pro Evolution.rar",
	"Iss Soccer Pro 98.7z",
	"Italian Job The.7z",
	"Jackie Chan Stuntmaster.7z",
	"Jade Cocoon Legend of Tamamayu.7z",
	"James Bond 007 Racing.7z",
	"James Bond 007 The World Is Not Enough.7z",
	"James Bond 007 Tomorrow Never Dies.7z",
	"Jarrett Labonte Stock Car Racing.7z",
	"Jeopardy 2Nd Edition.7z",
	"Jeopardy.7z",
	"Jeremy McGrath Supercross 2000.7z",
	"Jeremy McGrath Supercross 98.7z",
	"Jersey Devil.7z",
	"Jet Moto 2.7z",
	"Jet Moto 3.7z",
	"Jet Moto.7z",
	"Jigsaw Madness.7z",
	"Jimmy Johnson S Vr Football 98.7z",
	"Jimmy White S 2 Cueball.7z",
	"Johnny Bazookatone.7z",
	"Jojo S Bizarre Adventure.7z",
	"Judge Dredd.7z",
	"Juggernaut.7z",
	"Juggernaut.7z",
	"Juggernaut.7z",
	"Jumping Flash 2 Big Trouble In.7z",
	"Jumping Flash.7z",
	"Jumpstart Wildlife Safari.7z",
	"Jupiter Strike.7z",
	"K 1 Grand Prix.rar",
	"K 1 Revenge.rar",
	"K 1 The Arena Fighters In The Red Corner.rar",
	"Kagero Deception II.rar",
	"Kartia The Word of Fate.rar",
	"Kensei Sacred Fist.rar",
	"Kickboxing.rar",
	"Kileak The Dna Imperative.rar",
	"Killer Loop.rar",
	"Killing Zone.rar",
	"King of Fighters 95.rar",
	"King of Fighters 99.rar",
	"King S Field II.rar",
	"King S Field.rar",
	"Kingsley S Adventure.rar",
	"Kiss Pinball.7z",
	"Klonoa Door to Phantomile.rar",
	"Knockout Kings 2000.rar",
	"Knockout Kings 2001.rar",
	"Knockout Kings.rar",
	"Konami Arcade Classics.rar",
	"Koudelka Disc1Of4.rar",
	"Koudelka Disc2Of4.rar",
	"Koudelka Disc3Of4.rar",
	"Koudelka Disc4Of4.rar",
	"Krazy Ivan.rar",
	"Kurt Warner S Arena Football Unleashed.rar",
	"Land Before Time Big Water Adventure Bin.rar",
	"Land Before Time Return to The Great Valley Mdf.rar",
	"Land Before Time The Great Valley Racing Adventure Bin.rar",
	"Largo Winch Bin.rar",
	"League of Pain Professional Underground Bin Scus 94551 .Rar.rar",
	"Legacy of Kain Soul Reaver Bin.rar",
	"Legend of Dragoon The Iso Disc1Of4.rar",
	"Legend of Dragoon The Iso Disc2Of4.rar",
	"Legend of Dragoon The Iso Disc3Of4.rar",
	"Legend of Dragoon The Iso Disc4Of4.rar",
	"Legend of Legaia Ccd Scus 94254 .Rar.rar",
	"Legend of Mana Ccd.rar",
	"Lego Island 2 Mdf.rar",
	"Lego Racers Mdf.rar",
	"Lego Rock Raiders Bin.rar",
	"Lemmings 3D Bin Scus 94601 .Rar.rar",
	"Lemmings Oh No More Lemmings Cdi.rar",
	"Lethal Enforcers I II Ccd.rar",
	"Loaded Bin.rar",
	"Lode Runner Bin.rar",
	"Looney Toons Racing Bin.rar",
	"Looney Toons Sheep Raider Bin.rar",
	"Lost World The Jurassic Park Ccd.rar",
	"Lucky Luke Bin.rar",
	"Lunar 2 Eternal Blue Complete Bin Disc1Of3.rar",
	"Lunar 2 Eternal Blue Complete Bin Disc2Of3.rar",
	"Lunar 2 Eternal Blue Complete Bin Making of Disc.rar",
	"Lunar 2 Eternal Blue Complete Ccd Disc3Of3.rar",
	"Lunar Silver Star Story Complete Ccd Disc1Of2.rar",
	"Lunar Silver Star Story Complete Ccd Disc2Of2.rar",
	"Lunar Silver Star Story Complete Ccd Making of Disc.rar",
	"M M Shell Shocked.rar",
	"Machine Head.zip",
	"Machine Hunter.rar",
	"Madden Nfl 2000.rar",
	"Madden Nfl 2001.rar",
	"Madden Nfl 2002.rar",
	"Madden Nfl 2003.rar",
	"Madden Nfl 2004.rar",
	"Madden Nfl 2005.rar",
	"Madden Nfl 96 Unreleased .Rar.rar",
	"Madden Nfl 97.rar",
	"Madden Nfl 98.rar",
	"Madden Nfl 99.rar",
	"Magic Carpet.rar",
	"Magic The Gathering Battlemage.rar",
	"Marble Master.rar",
	"Martian Gothic.rar",
	"Marvel Super Heroes.rar",
	"Marvel Super Heroes Vs Street Fighter.rar",
	"Marvel Vs. Capcom Clash of The Super Heroes.rar",
	"Mary Kate Ashley Olsen Crush Course.rar",
	"Mary Kate Ashley Olsen Magic Mystery Mall.rar",
	"Mary Kate Ashley Olsen Winners Circle.rar",
	"Mass Destruction.rar",
	"Masters of Monsters Diciples of Gaia.rar",
	"Matt Hoffman S Pro Bmx.rar",
	"Maximum Force.rar",
	"McGrath Vs. Pastrana Freestyle Motocross.rar",
	"Mdk.rar",
	"Mechwarrior 2.rar",
	"Medal of Honor.rar",
	"Medal of Honor Underground.rar",
	"Medievil II Scus 94564 .Rar.rar",
	"Medievil Scus 94227 .Rar.rar",
	"Megaman 8.rar",
	"Megaman Legends 2.rar",
	"Megaman Legends.rar",
	"Megaman X4.rar",
	"Megaman X5.rar",
	"Megaman X6.rar",
	"Men In Black The Series Crashdown.zip",
	"Metal Gear Solid Disc1Of2.rar",
	"Metal Gear Solid Disc2Of2.rar",
	"Metal Gear Solid Vr Missions.rar",
	"Metal Slug X.7z",
	"Micro Machines V3.zip",
	"Micro Maniacs Racing.rar",
	"Mike Tyson Boxing.rar",
	"Millenium Soldier Expendable.rar",
	"Miracle Space Race.rar",
	"Misadventures of Tron Bonne The.7z",
	"Miss Spider S Tea Party.rar",
	"Missile Command.7z",
	"Mission Impossible.7z",
	"Mlb 2005.7z",
	"Mlb 99.rar",
	"Mlb Pennant Race.rar",
	"Mm Airace.7Z.7z",
	"Mm Dball.7Z.7z",
	"Mobil 1 Rally Championship.rar",
	"Mobile Armor.rar",
	"Mobile Light Force.rar",
	"Monaco Grand Prix.rar",
	"Monkey Hero.rar",
	"Monkey Magic.rar",
	"Monopoly.rar",
	"Monster Bass.rar",
	"Monster Rancher 2.rar",
	"Monster Rancher Battle Card Episode II.rar",
	"Monster Rancher Hop a Bout.rar",
	"Monster Rancher.rar",
	"Monsters Inc. Scream Team.rar",
	"Monsterseed.rar",
	"Mort The Chicken.rar",
	"Mortal Kombat 3.rar",
	"Mortal Kombat 4.rar",
	"Mortal Kombat Mythologies Sub Zero 0.zip",
	"Mortal Kombat Special Forces.rar",
	"Mortal Kombat Trilogy.rar",
	"Moto Racer 2.rar",
	"Moto Racer.rar",
	"Moto Racer World Tour.rar",
	"Motocross Mania 2.7z",
	"Motocross Mania.rar",
	"Motor Toon Grand Prix.rar",
	"Motorhead.zip",
	"Mr. Domino No One Can Stop.zip",
	"Mr. Driller.rar",
	"Ms. Pacman Maze Madness.rar",
	"Mtv Celebrity Deathmatch.rar",
	"Mtv Music Generator.rar",
	"Mtv Sports Pure Ride.rar",
	"Mtv Sports Skateboarding Featuring Andy Macdonald.rar",
	"Mtv Sports Tj Lavin S Ultimate Bmx.rar",
	"Mummy The.rar",
	"Muppet Monster Adventure.rar",
	"Muppet Race Mania.rar",
	"My Disney Kitchen.7z",
	"Myst.rar",
	"N Gen Racing.rar",
	"N2O Nitrous Oxide.rar",
	"Nagano Winter Olympics 98.rar",
	"Namco Museum Vol.1.rar",
	"Namco Museum Vol.2.rar",
	"Namco Museum Vol.3.rar",
	"Namco Museum Vol.4.rar",
	"Namco Museum Vol.5.rar",
	"Nanotek Warrior.rar",
	"Nascar 2000.rar",
	"Nascar 2001.rar",
	"Nascar 98 Collector S Edition.rar",
	"Nascar 98.rar",
	"Nascar 99 Legacy.rar",
	"Nascar 99.rar",
	"Nascar Heat.rar",
	"Nascar Racing.rar",
	"Nascar Rumble.rar",
	"Nascar Thunder 2002.rar",
	"Nascar Thunder 2003.rar",
	"Nascar Thunder 2004.rar",
	"Nba Basketball 2000.rar",
	"Nba Fastbreak 98.rar",
	"Nba Hangtime.rar",
	"Nba Hoopz.rar",
	"Nba In The Zone 2.rar",
	"Nba In The Zone 2000.rar",
	"Nba In The Zone 98.rar",
	"Nba In The Zone 99.rar",
	"Nba In The Zone.rar",
	"Nba Jam Extreme.rar",
	"Nba Jam T.e..rar",
	"Nba Live 2000.rar",
	"Nba Live 2001.rar",
	"Nba Live 2002.rar",
	"Nba Live 2003.rar",
	"Nba Live 96.rar",
	"Nba Live 97.rar",
	"Nba Live 98.rar",
	"Nba Live 99.rar",
	"Nba Shootout 2000.rar",
	"Nba Shootout 2001.rar",
	"Nba Shootout 2002.rar",
	"Nba Shootout 2003.zip",
	"Nba Shootout 2004.rar",
	"Nba Shootout 97.rar",
	"Nba Shootout 98.rar",
	"Nba Shootout.rar",
	"Nba Showtime Nba On Nbc.rar",
	"Ncaa Basketball Final Four 97.rar",
	"Ncaa Final Four 2000.rar",
	"Ncaa Final Four 2001.rar",
	"Ncaa Final Four 99 Scus 94264 .Rar.rar",
	"Ncaa Football 2000.rar",
	"Ncaa Football 2001.rar",
	"Ncaa Football 98.rar",
	"Ncaa Football 99.rar",
	"Ncaa Football Gamebreaker.rar",
	"Ncaa Gamebreaker 2000 Scus 94557 .Rar.rar",
	"Ncaa Gamebreaker 2001.rar",
	"Ncaa Gamebreaker 98.rar",
	"Ncaa Gamebreaker 99.rar",
	"Ncaa March Madness 2000.rar",
	"Ncaa March Madness 2001.rar",
	"Ncaa March Madness 98.rar",
	"Ncaa March Madness 99.rar",
	"Nectaris Military Madness.rar",
	"Need For Speed 4 High Stakes.rar",
	"Need For Speed 5 Porsche Unleashed.rar",
	"Need For Speed II.rar",
	"Need For Speed III Hot Pursuit.rar",
	"Need For Speed.rar",
	"Need For Speed V Rally 2.rar",
	"Need For Speed V Rally.rar",
	"Newman Haas Racing.rar",
	"Next Tetris The.rar",
	"Nfl Blitz 2000.rar",
	"Nfl Blitz 2001.7z",
	"Nfl Blitz.rar",
	"Nfl Full Contact.rar",
	"Nfl Gameday 2000.rar",
	"Nfl Gameday 2001.rar",
	"Nfl Gameday 2002.rar",
	"Nfl Gameday 2003.rar",
	"Nfl Gameday 2004.rar",
	"Nfl Gameday 2005.rar",
	"Nfl Gameday 97.rar",
	"Nfl Gameday 98.rar",
	"Nfl Gameday 99.rar",
	"Nfl Gameday.rar",
	"Nfl Quarterback Club 97.rar",
	"Nfl Xtreme 2.rar",
	"Nfl Xtreme.rar",
	"Nhl 2000.rar",
	"Nhl 2001.rar",
	"Nhl 97.zip",
	"Nhl 98.rar",
	"Nhl 99.rar",
	"Nhl Blades of Steel 2000.rar",
	"Nhl Breakaway 98.rar",
	"Nhl Faceoff 2000.rar",
	"Nhl Faceoff 2001.rar",
	"Nhl Faceoff 97.rar",
	"Nhl Faceoff 98.rar",
	"Nhl Faceoff 99.rar",
	"Nhl Faceoff.rar",
	"Nhl Open Ice.rar",
	"Nhl Powerplay 96.rar",
	"Nhl Powerplay 98.rar",
	"Nhl Rock The Rink.rar",
	"Nicktoons Racing.rar",
	"Nightmare Creatures II.rar",
	"Nightmare Creatures.rar",
	"Ninja Shadow of Darkness.rar",
	"Nofear Downhill Mountain Bike Racing.rar",
	"Norse By Norsewest Return of The Lost Vikings.rar",
	"Novastorm Disc1Of2.rar",
	"Novastorm Disc2Of2.rar",
	"Nuclear Strike.rar",
	"Oddworld Abe S Exoddus.7z",
	"Oddworld Abe S Exoddus.7z",
	"Oddworld Abe S Oddysee.7z",
	"Odt Escape Or Die Trying.7z",
	"Off World Interceptor Extreme.7z",
	"Ogre Battle Ep.5 The March of The Black Queen Limited Edition.7z",
	"Ogre Battle Ep.5 The March of The Black Queen Limited Edition.7z",
	"Olympic Soccer.7z",
	"Olympic Summer Games.7z",
	"Omega Boost.7z",
	"One.7z",
	"One Piece Mansion.7z",
	"Overblood.7z",
	"Pac Man World 20Th Anniversary.zip",
	"Pajama Sam You Are What You Eat From Your Head to Your Feet.rar",
	"Pandemonium 2.rar",
	"Pandemonium.rar",
	"Panzer Front.zip",
	"Panzer General.rar",
	"Parappa The Rapper.rar",
	"Parasite Eve 2 Disc1Of2.rar",
	"Parasite Eve 2 Disc2Of2.rar",
	"Parasite Eve Disc1Of2.rar",
	"Parasite Eve Disc2Of2.rar",
	"Patriotic Pinball.rar",
	"Peak Performance.rar",
	"Perfect Weapon.rar",
	"Persona 2 Eternal Punishment Bonus Disc.zip",
	"Persona 2 Eternal Punishment.rar",
	"Persona Revelations.rar",
	"Pga Tour 96.rar",
	"Pga Tour 97.rar",
	"Pga Tour 98.rar",
	"Philosoma.rar",
	"Pinobee.rar",
	"Pipe Dreams 3D.rar",
	"Pitball.rar",
	"Pitfall 3D Beyond The Jungle.rar",
	"Pizza Hut Pizza Powered Demo.rar",
	"Planet of The Apes.rar",
	"Play With The Teletubbies.rar",
	"Po Ed.rar",
	"Pocket Fighter.rar",
	"Point Blank 2.rar",
	"Point Blank 3 Game Only.rar",
	"Point Blank.rar",
	"Polaris Snowcross.7z",
	"Pong 3D The Next Level.rar",
	"Pool Hustler.7z",
	"Populous The Beginning.zip",
	"Porsche Challenge.rar",
	"Power Move Pro Wrestling.rar",
	"Power Play Sports Trivia.7z",
	"Power Rangers Lightspeed Rescue.zip",
	"Power Rangers Time Force.rar",
	"Power Rangers Zeo Full Tilt Battle Pinball.rar",
	"Power Serve 3D Tennis.rar",
	"Power Shovel.rar",
	"Powerboat Racing.rar",
	"Powerpuff Girls Chemical X Traction.7z",
	"Powerslave.7z",
	"Powerspike Pro Beach Volleyball.zip",
	"Poypoy.rar",
	"Primal Rage.rar",
	"Pro 18 World Tour Golf.zip",
	"Pro Pinball Big Race Usa.7z",
	"Pro Pinball Fantastic Journey.rar",
	"Pro Pinball The Web.rar",
	"Pro Pinball Timeshock.rar",
	"Project Horned Owl.rar",
	"Project Overkill.rar",
	"Psybadek.7z",
	"Psychic Detective Disc1Of3.rar",
	"Psychic Detective Disc2Of3.rar",
	"Psychic Detective Disc3Of3.rar",
	"Psychic Force.rar",
	"Punky Skunk.rar",
	"Putter Golf.rar",
	"Puzznic.rar",
	"Q Bert.7z",
	"Qix Neo.7z",
	"Quake II.7z",
	"R Type Delta.7z",
	"R Types.7z",
	"Racing.7z",
	"Rage Racer.rar",
	"Rageball.7z",
	"Raiden Project.7z",
	"Railroad Tycoon II.7z",
	"Rally Cross 2.rar",
	"Rally Cross.7z",
	"Rally Master.7z",
	"Rampage 2 Universal Tour.7z",
	"Rampage Through Time.7z",
	"Rampage World Tour.rar",
	"Rascal Racers.rar",
	"Rascal.rar",
	"Rat Attack.7z",
	"Ray Tracers.rar",
	"Raycrisis Series Termination.rar",
	"Rayman 2 The Great Escape.rar",
	"Rayman Brain Games.7z",
	"Rayman Rush.7z",
	"Rayman.rar",
	"Raystorm.7z",
	"Razor Freestyle Scooter.7z",
	"Razor Scootin Racing.7z",
	"Rc de Go.7z",
	"Rc Helicopter.7z",
	"Rc Revenge.rar",
	"Rc Stunt Copter.zip",
	"Re Loaded.rar",
	"Re Volt Racing Out of Control.rar",
	"Ready 2 Rumble Boxing Round 2.7z",
	"Ready 2 Rumble.7z",
	"Reboot.rar",
	"Red Asphalt.rar",
	"Reel Fishing II.7z",
	"Reel Fishing.rar",
	"Renegade Racers.7z",
	"Rescue Copter.7z",
	"Rescue Heroes Molten Menace.7z",
	"Resident Evil 2 Cd1.7z",
	"Resident Evil 2 Cd2.7z",
	"Resident Evil 2 Dual Shock Cd1.7z",
	"Resident Evil 2 Dual Shock Cd2.7z",
	"Resident Evil 3 Nemesis.7z",
	"Resident Evil Director S Cut Dual Shock.rar",
	"Resident Evil Director S Cut.rar",
	"Resident Evil Survivor.rar",
	"Resident Evil.7z",
	"Return Fire.rar",
	"Revolution X.rar",
	"Rhapsody a Musical Adventure.rar",
	"Ridge Racer Revolution.rar",
	"Ridge Racer Type 4 Bonus Disc.7z",
	"Ridge Racer Type 4.rar",
	"Ridge Racer.7z",
	"Rise of Robots 2 Resurection.7z",
	"Rising Zan The Samurai Gunman.7z",
	"Risk.7z",
	"Rival Schools Arcade Disc.rar",
	"Rival Schools Evolution.7z",
	"Riven The Sequel to Myst Cd1.rar",
	"Riven The Sequel to Myst Cd2.rar",
	"Riven The Sequel to Myst Cd3.rar",
	"Riven The Sequel to Myst Cd4.rar",
	"Riven The Sequel to Myst Cd5.rar",
	"Road Rash 3D.7z",
	"Road Rash Jailbreak.rar",
	"Road Rash.rar",
	"Roadsters.7z",
	"Robopit 2.rar",
	"Robopit.rar",
	"Robotron X.rar",
	"Rock em Sock em Robots Arena.rar",
	"Rocket Power Team Rocket Rescue.7z",
	"Rogue Trip Vacation 2012.rar",
	"Roll Away.rar",
	"Rollcage Stage II.7z",
	"Rollcage.rar",
	"Romance of The Three Kingdoms IV Wall of Fire.rar",
	"Romance of The Three Kingdoms VI.7z",
	"Rosco McQueen Fire Fighter Extreme.7z",
	"Roswell Conspiracies.rar",
	"Rpg Maker.7z",
	"Rugrats In Paris The Movie.7z",
	"Rugrats Search For Reptar.rar",
	"Rugrats Studio Tour.rar",
	"Rugrats Totally Angelica.7z",
	"Runabout 2.rar",
	"Running Wild.7z",
	"Rush Hour.rar",
	"Rushdown.rar",
	"S.C.a.R.S..rar",
	"Sabrina The Teenage Witch a Twitch In Time.rar",
	"Saga Frontier II.rar",
	"Saga Frontier.rar",
	"Saiyuki Journey West.rar",
	"Saltwater Sportfishing.rar",
	"Sammy Sosa High Heat Baseball 2001.rar",
	"Sammy Sosa Softball Slam.7z",
	"Samurai Showdown III.rar",
	"Samurai Showdown Warrior S Rage.rar",
	"San Francisco Rush Extreme Racing.rar",
	"Scooby Doo The Cyber Chase.rar",
	"Scrabble.rar",
	"Sea Doo Hydrocross.rar",
	"Sentient.rar",
	"Sentinel Returns.rar",
	"Shadow Madness Disc1Of2.rar",
	"Shadow Madness Disc2Of2.rar",
	"Shadow Man.7z",
	"Shadow Tower King S Field III.rar",
	"Shanghai True Valor.rar",
	"Sheep.rar",
	"Shellshock.rar",
	"Shipwreckers.rar",
	"Shockwave Assault.rar",
	"Shockwave Operation Jumpgate.rar",
	"Shrek Treasure Hunt.7z",
	"Silent Bomber.rar",
	"Silent Hill.rar",
	"Silhouette Mirage.rar",
	"Silverload.rar",
	"Sim City 2000.rar",
	"Sim Theme Park.7z",
	"Simpsons Wrestling.rar",
	"Skeleton Warriors.rar",
	"Skullmonkeys.rar",
	"Skydiving Extreme.rar",
	"Slam N Jam 96.rar",
	"Slamscape.rar",
	"Sled Storm.rar",
	"Slots.rar",
	"Small Soldiers.rar",
	"Smurf Racer.7z",
	"Smurfs The.rar",
	"Sno Cross Championship Racing.rar",
	"Snowboarding.rar",
	"Sol Divide.rar",
	"Sorcerer S Maze.7z",
	"Soul Blade.zip",
	"Soul of The Samurai.rar",
	"South Park Chef S Luv Shack.rar",
	"South Park Rally.rar",
	"South Park.rar",
	"Soviet Strike.rar",
	"Space Griffon Vf 9.rar",
	"Space Hulk Vengeance of The Blood Angels.zip",
	"Space Invaders.rar",
	"Space Jam.rar",
	"Space Shot.rar",
	"Spawn The Eternal.rar",
	"Spec Ops Airborne Commando.rar",
	"Spec Ops Covert Assault.rar",
	"Spec Ops Ranger Elite.rar",
	"Spec Ops Stealth Patrol.rar",
	"Speed Punks.rar",
	"Speed Racer.rar",
	"Speedball 2100.rar",
	"Spice World.rar",
	"Spider The Video Game.rar",
	"Spiderman 2 Enter Electro.rar",
	"Spiderman.rar",
	"Spin Jam.rar",
	"Spongebob Squarepants Supersponge.7z",
	"Sports Car Supreme Gt.rar",
	"Spot Goes to Hollywood.rar",
	"Spyro The Dragon 2 Ripto S Rage.rar",
	"Spyro The Dragon 3 Year of The Dragon.rar",
	"Spyro The Dragon.rar",
	"Star Fighter.rar",
	"Star Gladiator Episode 1 Final Crusade.rar",
	"Star Ocean The Second Story Disc1Of2.rar",
	"Star Ocean The Second Story Disc2Of2.rar",
	"Star Sweep.rar",
	"Star Trek Invasion.rar",
	"Star Wars Dark Forces.rar",
	"Star Wars Demolition.rar",
	"Star Wars Episode I Jedi Power Battle.rar",
	"Star Wars Episode I The Phantom Menace.rar",
	"Star Wars Masters of Teras Kasi.rar",
	"Star Wars Rebel Assault II Disc1Of2.rar",
	"Star Wars Rebel Assault II Disc2Of2.rar",
	"Starblade Alpha.rar",
	"Starfighter Sanvein.7z",
	"Starwinder The Ultimate Space Race.rar",
	"Steel Harbinger.rar",
	"Steel Reign.rar",
	"Streak Hoverboard Racing.rar",
	"Street Fighter Alpha 2.rar",
	"Street Fighter Alpha 3.rar",
	"Street Fighter Alpha Warriors Dreams.rar",
	"Street Fighter Collection 2.rar",
	"Street Fighter Collection Disc1Of2.rar",
	"Street Fighter Collection Disc2Of2 Street Fighter Alpha 2 Gold.rar",
	"Street Fighter Ex Plus Alpha.rar",
	"Street Fighter Ex2 Plus.rar",
	"Street Fighter The Movie.rar",
	"Street Racer.rar",
	"Street Racquetball.rar",
	"Street Sk8Er 2.rar",
	"Street Sk8Er.rar",
	"Strider 2.rar",
	"Strider.rar",
	"Strike Point.rar",
	"Striker Pro 2000.rar",
	"Striker.rar",
	"Strikers 1945.7z",
	"Stuart Little 2.rar",
	"Suikoden II.rar",
	"Suikoden.rar",
	"Super Bubble Pop.rar",
	"Super Puzzle Fighter II Turbo.zip",
	"Super Shot Soccer.rar",
	"Superbikes 2000.7z",
	"Supercross 2000.zip",
	"Supercross 2001.zip",
	"Supercross Circuit.rar",
	"Superstar Dance Club.rar",
	"Surf Riders.rar",
	"Swagman.rar",
	"Sydney 2000.rar",
	"Syndicate Wars.rar",
	"Syphon Filter 2 Disc1Of2.rar",
	"Syphon Filter 2 Disc2Of2.rar",
	"Syphon Filter 3.rar",
	"Syphon Filter.rar",
	"T Ai Fu Wrath of The Tiger.7z",
	"T.R.a.G. Tactical Rescue Assauls Group Mission of Mercy.7z",
	"Tactics Ogre Let Us Cling Together.7z",
	"Tail Concerto.7z",
	"Tail of The Sun Wild Pure Simple Life.7z",
	"Tales of Destiny II Tales of Eternia 3 Discs.7z",
	"Tales of Destiny.7z",
	"Tall Infinity The Tower of Wisdom.7z",
	"Team Buddies.7z",
	"Team Losi Rc Racer.7z",
	"Tecmo S Deception Invitation to Darkness.7z",
	"Tecmo Stackers.rar",
	"Tecmo Super Bowl.7z",
	"Tecmo World Golf Japan.7z",
	"Tekken 2.7z",
	"Tekken 3.7z",
	"Tekken.7z",
	"Tempest X3.7z",
	"Ten Pin Alley.7z",
	"Tenchu 2 Birth of The Stealth Assassins.7z",
	"Tenchu Stealth Assassins.7z",
	"Tennis Arena.7z",
	"Tennisa1.rar",
	"Test Drive 4.7z",
	"Test Drive 5.7z",
	"Test Drive 6.7z",
	"Test Drive Le Mans.7z",
	"Test Drive Off Road 2.7z",
	"Test Drive Off Road 3.7z",
	"Test Drive Off Road.rar",
	"Tetris Plus.7z",
	"Theme Hospital.7z",
	"Theme Park.7z",
	"Thousand Arms 2Discs.7z",
	"Thrasher Skate Destroy.7z",
	"Threads of Fate.7z",
	"Three Stooges The.7z",
	"Thrill Kill Slus00752 .Rar.rar",
	"Thunder Force V Perfect System.7z",
	"Thunder Truck Rally.7z",
	"Thunderstrike 2.rar",
	"Tiger Woods Pga Tour 2000.7z",
	"Tiger Woods Pga Tour Golf 99.7z",
	"Tiger Woods Pga Tour Golf.7z",
	"Tigershark.7z",
	"Time Commando.7z",
	"Time Crisis II Project Titan.7z",
	"Time Crisis.rar",
	"Tiny Tank.7z",
	"Tiny Toon Adventures Plucky S Great Adventure.7z",
	"Tiny Toon Adventures The Great Beanstalk.7z",
	"Tiny Toon Adventures Toonenstein Dare to Scare.7z",
	"Tnn Hardcore 4X4.rar",
	"Tnn Motorsports Hardcore Tr.rar",
	"Tobal No.1.rar",
	"Toca Championship Racing.7z",
	"Toca Touring Car Challenge 2.7z",
	"Tokyo Highway Battle.7z",
	"Tom Clancy S Rainbow Six Lone Wolf.7z",
	"Tom Clancy S Rainbow Six Rogue Spear.7z",
	"Tom Clancy S Rainbow Six.7z",
	"Tom Jerry House Trap.7z",
	"Tomb Raider 2.7z",
	"Tomb Raider 3 Adventures of Lara Croft.7z",
	"Tomb Raider 4 The Last Revelation.7z",
	"Tomb Raider 5 Chronicles.7z",
	"Tomb Raider Greatest Hits.7z",
	"Tomba 2 The Evil Swine Returns.7z",
	"Tomba.7z",
	"Tonka Space Station.7z",
	"Tony Hawk S Pro Skater 2.7z",
	"Tony Hawk S Pro Skater 4.7z",
	"Tony Hawk S Pro Skater.7z",
	"Tony Hawks Pro Skater 3.7z",
	"Top Gun Fire At Will.7z",
	"Top Shop.7z",
	"Torc Legend of The Ogre Crown.7z",
	"Torneko The Last Hope World of Dragon Warrior.7z",
	"Total Eclipse Turbo.7z",
	"Transformers Beast Wars Transmetals.7z",
	"Trap Gunner.7z",
	"Treasures of The Deep.7z",
	"Trick N Snowboarder.7z",
	"Triple Play 2000.7z",
	"Triple Play 2001.7z",
	"Triple Play 97.7z",
	"Triple Play 98.7z",
	"Triple Play 99.7z",
	"Triple Play Baseball.7z",
	"True Pinball.7z",
	"Tunnel B1.7z",
	"Turbo Prop Racing.7z",
	"Turnabout.7z",
	"Twisted Metal 2 Scus 94306 Bin .Rar.rar",
	"Twisted Metal 3.7z",
	"Twisted Metal 4.7z",
	"Twisted Metal Scus 94304 Bin .Rar.rar",
	"Twisted Metal Small Brawl.7z",
	"Tyco.Rc.Assault.With.a.Battery.rar",
	"Ultimate 8 Ball.zip",
	"Ultimate Brain Games.zip",
	"Ultimate Fighting Championship.zip",
	"Um Jammer Lammy.rar",
	"Unholy War The.rar",
	"Uprising X.zip",
	"Urban Chaos.zip",
	"Vagrant Story.rar",
	"Valkyrie Profile Disc1Of2.rar",
	"Valkyrie Profile Disc2Of2.rar",
	"Vampire Hunter D.rar",
	"Vanark Astro Trooper.rar",
	"Vandal Hearts II.rar",
	"Vandal Hearts.7z",
	"Vanguard Bandits.rar",
	"Vanishing Point.zip",
	"Vegas Games 2000.rar",
	"Viewpoint.rar",
	"Vigilante 8 2Nd Offense.7z",
	"Vigilante 8.7z",
	"Vip.7z",
	"Virtual Kasparov.rar",
	"Virtual Open Tennis.Rar.rar",
	"Virtual Pool 3.rar",
	"Virtual Pool.rar",
	"Viva Soccer.Zip.zip",
	"Vmx Racing.rar",
	"Vr Baseball 97.rar",
	"Vr Baseball 99.7z",
	"Vr Golf 97.rar",
	"Vr Soccer 96.rar",
	"Vs..rar",
	"War Games Defcon 1.7z",
	"War Gods.7z",
	"Warcraft II The Dark Saga.7z",
	"Warhammer Dark Omen.7z",
	"Warhammer Shadow of The Horned Rat.7z",
	"Warhawk The Red Mercury Missions.7z",
	"Warpath Jurassic Park.7z",
	"Warriors of Might and Magic.7z",
	"Warzone 2100.7z",
	"Wayne Gretzky S 3D Hockey 98.7z",
	"Wcw Backstage Assault.7z",
	"Wcw Mayhem.7z",
	"Wcw Nitro.7z",
	"Wcw Nwo Thunder.7z",
	"Wcw Vs. The World.7z",
	"Wdl World Destruction League Thunder Tanks.7z",
	"Weakest Link.7z",
	"Wheel of Fortune 2Nd Edition.7z",
	"Wheel of Fortune.7z",
	"Who Wants to Be a Millionaire 2Nd Edition.7z",
	"Who Wants to Be a Millionaire 3Rd Edition.7z",
	"Wild 9.7z",
	"Wild Arms 2.7z",
	"Wild Arms 2.7z",
	"Wild Arms.7z",
	"Wild Thornberrys Animal Adventures.7z",
	"Wing Commander III Heart of The Tiger.7z",
	"Wing Commander III Heart of The Tiger.7z",
	"Wing Commander III Heart of The Tiger.7z",
	"Wing Commander III Heart of The Tiger.7z",
	"Wing Commander IV The Price of Freedom.7z",
	"Wing Commander IV The Price of Freedom.7z",
	"Wing Commander IV The Price of Freedom.7z",
	"Wing Commander IV The Price of Freedom.7z",
	"Winnie The Pooh Kindergarden.7z",
	"Winnie The Pooh Preschool.7z",
	"Wipeout 3.7z",
	"Wipeout.7z",
	"Wipeout Xl.7z",
	"Woody Woodpecker Racing.7z",
	"World Cup 98.7z",
	"World Cup Golf.7z",
	"World Destruction League War Jetz.7z",
	"World S Scariest Police Chases.7z",
	"Worms Armageddon.7z",
	"Worms.7z",
	"Worms World Party.7z",
	"Wreckin Crew.7z",
	"Wu Tang Shaolin Style.7z",
	"Wwf Attitude.7z",
	"Wwf In Your House.7z",
	"Wwf Smackdown 2 Know Your Role.7z",
	"Wwf Smackdown.7z",
	"Wwf Warzone.7z",
	"Wwf Wrestlemania The Arcade Game.7z",
	"X Bladez Inline Skater.7Z.7z",
	"X Com Ufo Defense.7z",
	"X Files 1Of4.7z",
	"X Files 2Of4.7z",
	"X Files 3Of4.7z",
	"X Men Academy.7z",
	"X Men Children of The Atom.7z",
	"X Men Mutant Academy 2.7z",
	"X Men Vs. Street Fighter.7z",
	"Xena Warrior Princess.7z",
	"Xenogears 1Of2.7z",
	"Xenogears 2Of2.7z",
	"Xevious 3D G.7z",
	"xploder.rar",
	"Xs Jr. League Soccer.7z",
	"Xs Junior League Dodgeball.7z",
	"Xs Moto.7z",
	"You Don T Know Jack 1Of2.7z",
	"You Don T Know Jack 2Of2.7z",
	"You Don T Know Jack.7z",
	"Yu Gi Oh Forbidden Memories.7Z.7z",
	"Zero Divide.7z",
	"Zoboomafoo Leapin Lemurs.7z",
	"Zoop.7z"];


foreach ($path_itens as $item) {
	
	$itemOriginal = $item;
	
	$ext = pathinfo($item, PATHINFO_EXTENSION);;
	
	$remove_all_after = [
		'-ntsc-',
		'-u-',
		'-slus-',
	
	];
	
	foreach ($remove_all_after as $filter) {
		$item = preg_replace("/$filter.*/", '', $item);
	};
	
	
	$item = str_replace('-', ' ', $item);
	
	$item = TitleCaseReplace::convert($item);
	
	if (file_exists($path . "/" . $item)) {
		$names[] = $itemOriginal;
		continue;
	}
	
	$names[] = TitleCaseReplace::convert($item) . "." . $ext;
	
	//rename($path . "/" . $itemOriginal, $path . "/" . $item);
	
};
